import Entity from '@/shared/core/domain/Entity';
import UniqueEntityID from '@/shared/core/domain/UniqueEntityID';
import GenericAppError from '@/shared/core/logic/GenericAppError';
import GenericErrors from '@/shared/core/logic/GenericErrors';
import Guard from '@/shared/core/logic/guard';
import { PartialAutoGenerated } from '@/shared/types/common';
import { BreedModel } from '@prisma/client';
import Specie from './specie.domain';

interface IBreedProps extends PartialAutoGenerated<Pick<BreedModel, 'name'>> {
  sequence?: number | null;
  associationId?: UniqueEntityID;
  specieId?: UniqueEntityID;

  specie?: Specie;
}

export default class Breed extends Entity<IBreedProps> {
  constructor(props: IBreedProps, id?: UniqueEntityID) {
    super(props, id);
  }

  get id(): UniqueEntityID {
    return this._id;
  }

  get name(): string {
    return this.props.name;
  }

  get sequence(): number | null | undefined {
    return this.props.sequence;
  }

  get associationId(): UniqueEntityID | null | undefined {
    return this.props.associationId;
  }

  get specieId(): UniqueEntityID | null | undefined {
    return this.props.specieId;
  }

  get enabled(): boolean {
    return this.props.enabled;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get deleted(): boolean {
    return this.props.deleted;
  }

  get specie(): Specie | null | undefined {
    return this.props.specie;
  }

  public static create(props: IBreedProps, id?: UniqueEntityID): Breed | GenericAppError {
    const guardedProps = Guard.againstNullOrUndefinedBulk([
      { argument: props.associationId, argumentName: 'id da associação' },
      { argument: props.specieId, argumentName: 'id da espécie' },
    ]);

    if (!guardedProps.succeeded) {
      return new GenericErrors.InvalidParam(guardedProps.message);
    }

    const propsWithDefault = {
      enabled: true,
      ...props,
    };

    return new Breed(propsWithDefault, id);
  }
}
