import Entity from '@/shared/core/domain/Entity';
import UniqueEntityID from '@/shared/core/domain/UniqueEntityID';
import GenericAppError from '@/shared/core/logic/GenericAppError';
import GenericErrors from '@/shared/core/logic/GenericErrors';
import Guard from '@/shared/core/logic/guard';
import { PartialAutoGenerated } from '@/shared/types/common';
import { SpecieModel } from '@prisma/client';

interface ISpecieProps extends PartialAutoGenerated<Pick<SpecieModel, 'name'>> {
  sequence?: number | null;
  associationId?: UniqueEntityID;
}

export default class Specie extends Entity<ISpecieProps> {
  constructor(props: ISpecieProps, id?: UniqueEntityID) {
    super(props, id);
  }

  get id(): UniqueEntityID {
    return this._id;
  }

  get name(): string {
    return this.props.name;
  }

  get sequence(): number | null | undefined {
    return this.props.sequence;
  }

  get associationId(): UniqueEntityID | null | undefined {
    return this.props.associationId;
  }

  get enabled(): boolean {
    return this.props.enabled;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get deleted(): boolean {
    return this.props.deleted;
  }

  public static create(props: ISpecieProps, id?: UniqueEntityID): Specie | GenericAppError {
    const guardedProps = Guard.againstNullOrUndefinedBulk([
      { argument: props.associationId, argumentName: 'id da associação' },
    ]);

    if (!guardedProps.succeeded) {
      return new GenericErrors.InvalidParam(guardedProps.message);
    }

    const propsWithDefault = {
      enabled: true,
      ...props,
    };

    return new Specie(propsWithDefault, id);
  }
}
