import { File } from '@nest-lab/fastify-multer';
import { PictureModel } from '@prisma/client';

import Entity from '@/shared/core/domain/Entity';
import UniqueEntityID from '@/shared/core/domain/UniqueEntityID';
import GenericAppError from '@/shared/core/logic/GenericAppError';
import GenericErrors from '@/shared/core/logic/GenericErrors';
import Guard from '@/shared/core/logic/guard';
import { PartialAutoGenerated } from '@/shared/types/common';

interface IPictureProps extends PartialAutoGenerated<Pick<PictureModel, 'enabled' | 'originalName'>> {
  entityId: UniqueEntityID;
  sequence?: number;
  url?: string;
  path?: string;

  file?: File;
}

export default class Picture extends Entity<IPictureProps> {
  constructor(props: IPictureProps, id?: UniqueEntityID) {
    super(props, id);
  }

  get id(): UniqueEntityID {
    return this._id;
  }

  get entityId(): UniqueEntityID {
    return this.props.entityId;
  }

  get originalName(): string {
    return this.props.originalName;
  }

  get url(): string {
    return this.props.url;
  }

  set url(value: string) {
    this.props.url = value;
  }

  get path(): string {
    return this.props.path;
  }

  set path(value: string) {
    this.props.path = value;
  }

  get sequence(): number | null | undefined {
    return this.props.sequence;
  }

  get enabled(): boolean {
    return this.props.enabled;
  }

  get createdAt(): Date {
    return this.props.createdAt;
  }

  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  get deleted(): boolean {
    return this.props.deleted;
  }

  get file(): File {
    return this.props.file;
  }

  set file(value: File) {
    this.props.file = value;
    this.makePath();
  }

  makePath(): void {
    const uniqueName = `${Date.now()}-${this.file.originalname}`;
    const completePath = `acapra/${this.entityId.toValue()}/${uniqueName}`;
    this.path = completePath;
  }

  public static create(props: IPictureProps, id?: UniqueEntityID): Picture | GenericAppError {
    const guardedProps = Guard.againstNullOrUndefinedBulk([
      { argument: props.entityId, argumentName: 'id da entidade' },
      { argument: props.originalName, argumentName: 'nome original' },
    ]);

    if (!guardedProps.succeeded) {
      return new GenericErrors.InvalidParam(guardedProps.message);
    }

    const propsWithDefault = {
      enabled: true,
      ...props,
    };

    const picture = new Picture(propsWithDefault, id);

    if (props.file) {
      picture.makePath();
    }

    return picture;
  }
}
